version: "2"
run:
    timeout: 5m
    go: ""
    build-tags: []
    allow-parallel-runners: false
    allow-serial-runners: false
output:
    formats: {}
linters:
    enable:
        - errcheck
        - gofmt
        - goimports
        - govet
        - ineffassign
        - misspell
        - revive
        - staticcheck
        - unused
    default: none
formatters:
    enable:
        - gofmt
        - goimports
issues: {}
